apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      app: poi
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryrwm9547.azurecr.io/tripinsights/poi:latest
        envFrom:
          - secretRef:
              name: sql                                           
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: value1
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
spec:
  selector:
    app: poi
  ports:
    - port: 80
      name: http
      targetPort: 80